# --- Created by Slick DDL
To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table `adviser` (`user_id` BIGINT NOT NULL,`adviser_user_id` BIGINT NOT NULL,`status` INTEGER DEFAULT 1 NOT NULL,`token` VARCHAR(254),`created_user_id` BIGINT NOT NULL,`created_at` TIMESTAMP NOT NULL,`updated_user_id` BIGINT,`updated_at` TIMESTAMP NULL);
alter table `adviser` add constraint `pk_on_adviser_user_id_adviser_user_id` primary key(`user_id`,`adviser_user_id`);
create table `config` (`name` VARCHAR(254) NOT NULL PRIMARY KEY,`value` VARCHAR(254) NOT NULL,`description` VARCHAR(254));
create table `contact` (`user_id` BIGINT NOT NULL,`contact_user_id` BIGINT NOT NULL,`status` INTEGER DEFAULT 1 NOT NULL,`token` VARCHAR(254),`created_user_id` BIGINT NOT NULL,`created_at` TIMESTAMP NOT NULL,`updated_user_id` BIGINT,`updated_at` TIMESTAMP NULL);
alter table `contact` add constraint `pk_on_contact_user_id_contact_user_id` primary key(`user_id`,`contact_user_id`);
create table `country` (`country_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`code` VARCHAR(254) NOT NULL,`name` VARCHAR(254) NOT NULL,`active` BOOLEAN NOT NULL);
create unique index `idx_country_on_code_unique` on `country` (`code`);
create table `document_search` (`document_search_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`user_id` BIGINT NOT NULL,`name` VARCHAR(254) NOT NULL,`search_text` VARCHAR(254) NOT NULL,`created_user_id` BIGINT NOT NULL,`created_at` TIMESTAMP NOT NULL,`updated_user_id` BIGINT,`updated_at` TIMESTAMP NULL);
create table `document_tag` (`user_id` BIGINT NOT NULL,`user_tag_id` BIGINT NOT NULL,`document_id` BIGINT NOT NULL,`user_document_id` BIGINT NOT NULL,`created_user_id` BIGINT NOT NULL,`created_at` TIMESTAMP NOT NULL,`updated_user_id` BIGINT,`updated_at` TIMESTAMP NULL);
create table `document` (`document_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`name` VARCHAR(254) NOT NULL,`document_type` INTEGER NOT NULL,`file_type` INTEGER NOT NULL,`file_name` VARCHAR(254) NOT NULL,`physical_name` VARCHAR(254) NOT NULL,`description` VARCHAR(254),`signature` VARCHAR(254) NOT NULL,`created_user_id` BIGINT NOT NULL,`created_at` TIMESTAMP NOT NULL,`updated_user_id` BIGINT,`updated_at` TIMESTAMP NULL);
create table `domain` (`domain_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`industry_id` BIGINT NOT NULL,`name` VARCHAR(254) NOT NULL,`code` VARCHAR(254) NOT NULL,`description` VARCHAR(254),`created_user_id` BIGINT NOT NULL,`created_at` TIMESTAMP NOT NULL,`updated_user_id` BIGINT,`updated_at` TIMESTAMP NULL);
create unique index `idx_unique_on_skill_code` on `domain` (`code`);
create table `industry` (`industry_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`code` VARCHAR(254) NOT NULL,`name` VARCHAR(254) NOT NULL,`description` VARCHAR(254),`created_user_id` BIGINT NOT NULL,`created_at` TIMESTAMP NOT NULL,`updated_user_id` BIGINT,`updated_at` TIMESTAMP NULL);
create unique index `idx_unique_on_industry_code` on `industry` (`code`);
create table `membership` (`membership_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`name` VARCHAR(254) NOT NULL,`description` VARCHAR(254),`created_user_id` BIGINT NOT NULL,`created_at` TIMESTAMP NOT NULL,`updated_user_id` BIGINT,`updated_at` TIMESTAMP NULL);
create table `message_box` (`message_box_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`user_id` BIGINT NOT NULL,`message_box_type` INTEGER NOT NULL,`name` VARCHAR(254) NOT NULL,`created_user_id` BIGINT NOT NULL,`created_at` TIMESTAMP NOT NULL,`updated_user_id` BIGINT,`updated_at` TIMESTAMP NULL);
create table `message_recipient` (`user_id` BIGINT NOT NULL,`message_id` BIGINT NOT NULL,`read` BOOLEAN NOT NULL,`created_user_id` BIGINT NOT NULL,`created_at` TIMESTAMP NOT NULL,`updated_user_id` BIGINT,`updated_at` TIMESTAMP NULL);
alter table `message_recipient` add constraint `pk_on_message_recipient` primary key(`user_id`,`message_id`);
create table `message` (`message_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`parent_message_id` BIGINT,`sender_user_id` BIGINT NOT NULL,`editable` BOOLEAN DEFAULT true NOT NULL,`subject` VARCHAR(254) NOT NULL,`body` VARCHAR(1024),`created_user_id` BIGINT NOT NULL,`created_at` TIMESTAMP NOT NULL,`updated_user_id` BIGINT,`updated_at` TIMESTAMP NULL);
create table `skill` (`skill_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`industry_id` BIGINT NOT NULL,`name` VARCHAR(254) NOT NULL,`code` VARCHAR(254) NOT NULL,`description` VARCHAR(254),`created_user_id` BIGINT NOT NULL,`created_at` TIMESTAMP NOT NULL,`updated_user_id` BIGINT,`updated_at` TIMESTAMP NULL);
create unique index `idx_skill_on_code_unique` on `skill` (`code`);
create table `user_document` (`user_document_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`user_id` BIGINT NOT NULL,`document_id` BIGINT NOT NULL,`ownership_type` INTEGER NOT NULL,`can_copy` BOOLEAN DEFAULT false NOT NULL,`can_share` BOOLEAN DEFAULT true NOT NULL,`can_view` BOOLEAN DEFAULT true NOT NULL,`important` BOOLEAN DEFAULT false NOT NULL,`star` BOOLEAN DEFAULT false NOT NULL,`is_limited_share` BOOLEAN DEFAULT true NOT NULL,`created_user_id` BIGINT NOT NULL,`created_at` TIMESTAMP NOT NULL,`share_until_eod` TIMESTAMP NULL,`updated_user_id` BIGINT,`updated_at` TIMESTAMP NULL);
create table `user_membership` (`user_membership_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`user_id` BIGINT NOT NULL,`membership_id` BIGINT NOT NULL,`start_date` TIMESTAMP NOT NULL,`end_date` TIMESTAMP NULL,`active` BOOLEAN DEFAULT true NOT NULL,`description` VARCHAR(254),`created_user_id` BIGINT NOT NULL,`created_at` TIMESTAMP NOT NULL,`updated_user_id` BIGINT,`updated_at` TIMESTAMP NULL);
create table `user_message` (`user_id` BIGINT NOT NULL,`message_id` BIGINT NOT NULL,`message_box_id` BIGINT NOT NULL,`read` BOOLEAN DEFAULT false NOT NULL,`replied` BOOLEAN DEFAULT false NOT NULL,`important` BOOLEAN DEFAULT false NOT NULL,`star` BOOLEAN DEFAULT false NOT NULL,`created_user_id` BIGINT NOT NULL,`created_at` TIMESTAMP NOT NULL,`updated_user_id` BIGINT,`updated_at` TIMESTAMP NULL);
alter table `user_message` add constraint `pk_on_user_message` primary key(`user_id`,`message_id`,`message_box_id`);
create table `user_skill` (`user_id` BIGINT NOT NULL,`skill_id` BIGINT NOT NULL,`skill_level` INTEGER NOT NULL,`description_short` VARCHAR(254),`description_long` VARCHAR(254),`created_user_id` BIGINT NOT NULL,`created_at` TIMESTAMP NOT NULL,`updated_user_id` BIGINT,`updated_at` TIMESTAMP NULL);
alter table `user_skill` add constraint `pk_on_user_skill_user_id_skill_id` primary key(`user_id`,`skill_id`);
create table `user_tag` (`user_tag_Id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`user_id` BIGINT NOT NULL,`name` VARCHAR(254) NOT NULL,`created_user_id` BIGINT NOT NULL,`created_at` TIMESTAMP NOT NULL,`updated_user_id` BIGINT,`updated_at` TIMESTAMP NULL);
create table `user` (`user_id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,`first_name` VARCHAR(254) NOT NULL,`last_name` VARCHAR(254) NOT NULL,`email` VARCHAR(254) NOT NULL,`password` VARCHAR(254) NOT NULL,`country_id` BIGINT NOT NULL,`activationToken` VARCHAR(254) NOT NULL,`verified` BOOLEAN NOT NULL,`otp` VARCHAR(254),`otp_expired_at` TIMESTAMP NULL,`created_at` TIMESTAMP NOT NULL,`updated_at` TIMESTAMP NULL);
create unique index `idx_user_on_email_unique` on `user` (`email`);
alter table `adviser` add constraint `fk_on_adviser_adviser_user_id` foreign key(`adviser_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `adviser` add constraint `fk_on_adviser_created_user_id` foreign key(`created_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `adviser` add constraint `fk_on_adviser_updated_user_id` foreign key(`updated_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `contact` add constraint `fk_on_contact_contact_user_id` foreign key(`contact_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `contact` add constraint `fk_on_contact_created_user_id` foreign key(`created_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `contact` add constraint `fk_on_contact_updated_user_id` foreign key(`updated_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `document_search` add constraint `fk_on_document_search_created_user_id` foreign key(`created_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `document_search` add constraint `fk_on_document_search_updated_user_id` foreign key(`updated_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `document_search` add constraint `fk_on_document_search_user_id` foreign key(`user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `document_tag` add constraint `fk_on_document_tag_created_user_id` foreign key(`created_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `document_tag` add constraint `fk_on_document_tag_document_id` foreign key(`document_id`) references `document`(`document_id`) on update NO ACTION on delete NO ACTION;
alter table `document_tag` add constraint `fk_on_document_tag_tag_id` foreign key(`user_tag_id`) references `user_tag`(`user_tag_Id`) on update NO ACTION on delete NO ACTION;
alter table `document_tag` add constraint `fk_on_document_tag_updated_user_id` foreign key(`updated_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `document_tag` add constraint `fk_on_document_tag_user_document_id` foreign key(`user_document_id`) references `user_document`(`user_document_id`) on update NO ACTION on delete NO ACTION;
alter table `document_tag` add constraint `fk_on_document_tag_user_id` foreign key(`user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `document` add constraint `fk_on_document_created_user_id` foreign key(`created_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `document` add constraint `fk_on_document_updated_user_id` foreign key(`updated_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `domain` add constraint `fk_on_domain_created_user_id` foreign key(`created_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `domain` add constraint `fk_on_domain_updated_user_id` foreign key(`updated_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `domain` add constraint `fk_on_skill_industry_id` foreign key(`industry_id`) references `industry`(`industry_id`) on update NO ACTION on delete NO ACTION;
alter table `industry` add constraint `fk_on_industry_created_user_id` foreign key(`created_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `industry` add constraint `fk_on_industry_updated_user_id` foreign key(`updated_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `membership` add constraint `fk_on_membership_created_user_id` foreign key(`created_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `membership` add constraint `fk_on_membership_updated_user_id` foreign key(`updated_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `message_box` add constraint `fk_on_message_box_created_user_id` foreign key(`created_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `message_box` add constraint `fk_on_message_box_updated_user_id` foreign key(`updated_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `message_box` add constraint `fk_on_message_box_user_id` foreign key(`user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `message_recipient` add constraint `fk_on_message_recipient_created_user_id` foreign key(`created_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `message_recipient` add constraint `fk_on_message_recipient_message_id` foreign key(`message_id`) references `message`(`message_id`) on update NO ACTION on delete NO ACTION;
alter table `message_recipient` add constraint `fk_on_message_recipient_updated_user_id` foreign key(`updated_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `message_recipient` add constraint `fk_on_message_recipient_user_id` foreign key(`user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `message` add constraint `fk_on_message_created_user_id` foreign key(`created_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `message` add constraint `fk_on_message_message_id` foreign key(`parent_message_id`) references `message`(`message_id`) on update NO ACTION on delete NO ACTION;
alter table `message` add constraint `fk_on_message_sender_user_id` foreign key(`sender_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `message` add constraint `fk_on_message_updated_user_id` foreign key(`updated_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `skill` add constraint `fk_on_skill_created_user_id` foreign key(`created_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `skill` add constraint `fk_on_skill_updated_user_id` foreign key(`updated_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `skill` add constraint `fk_skill_on_industry_id` foreign key(`industry_id`) references `industry`(`industry_id`) on update NO ACTION on delete NO ACTION;
alter table `user_document` add constraint `fk_on_user_document_created_user_id` foreign key(`created_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `user_document` add constraint `fk_on_user_document_updated_user_id` foreign key(`updated_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `user_document` add constraint `fk_user_document_on_document_id` foreign key(`document_id`) references `document`(`document_id`) on update NO ACTION on delete NO ACTION;
alter table `user_document` add constraint `fk_user_document_on_user_id` foreign key(`user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `user_membership` add constraint `fk_on_membership_id` foreign key(`membership_id`) references `membership`(`membership_id`) on update NO ACTION on delete NO ACTION;
alter table `user_membership` add constraint `fk_on_user_id` foreign key(`user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `user_membership` add constraint `fk_on_user_membership_created_user_id` foreign key(`created_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `user_membership` add constraint `fk_on_user_membership_updated_user_id` foreign key(`updated_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `user_message` add constraint `fk_on_user_message_created_user_id` foreign key(`created_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `user_message` add constraint `fk_on_user_message_message_box_id` foreign key(`message_box_id`) references `message_box`(`message_box_id`) on update NO ACTION on delete NO ACTION;
alter table `user_message` add constraint `fk_on_user_message_message_id` foreign key(`message_id`) references `message`(`message_id`) on update NO ACTION on delete NO ACTION;
alter table `user_message` add constraint `fk_on_user_message_updated_user_id` foreign key(`updated_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `user_message` add constraint `fk_on_user_message_user_id` foreign key(`user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `user_skill` add constraint `fk_on_user_skill_created_user_id` foreign key(`created_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `user_skill` add constraint `fk_on_user_skill_skill_id` foreign key(`skill_id`) references `skill`(`skill_id`) on update NO ACTION on delete NO ACTION;
alter table `user_skill` add constraint `fk_on_user_skill_updated_user_id` foreign key(`updated_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `user_skill` add constraint `fk_on_user_skill_user_id` foreign key(`user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `user_tag` add constraint `fk_on_user_tag_created_user_id` foreign key(`created_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `user_tag` add constraint `fk_on_user_tag_updated_user_id` foreign key(`updated_user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `user_tag` add constraint `fk_on_user_tag_user_id` foreign key(`user_id`) references `user`(`user_id`) on update NO ACTION on delete NO ACTION;
alter table `user` add constraint `fk_on_user_country_id` foreign key(`country_id`) references `country`(`country_id`) on update NO ACTION on delete NO ACTION;

# --- !Downs

ALTER TABLE user DROP FOREIGN KEY fk_on_user_country_id;
ALTER TABLE user_tag DROP FOREIGN KEY fk_on_user_tag_created_user_id;
ALTER TABLE user_tag DROP FOREIGN KEY fk_on_user_tag_updated_user_id;
ALTER TABLE user_tag DROP FOREIGN KEY fk_on_user_tag_user_id;
ALTER TABLE user_skill DROP FOREIGN KEY fk_on_user_skill_created_user_id;
ALTER TABLE user_skill DROP FOREIGN KEY fk_on_user_skill_skill_id;
ALTER TABLE user_skill DROP FOREIGN KEY fk_on_user_skill_updated_user_id;
ALTER TABLE user_skill DROP FOREIGN KEY fk_on_user_skill_user_id;
ALTER TABLE user_message DROP FOREIGN KEY fk_on_user_message_created_user_id;
ALTER TABLE user_message DROP FOREIGN KEY fk_on_user_message_message_box_id;
ALTER TABLE user_message DROP FOREIGN KEY fk_on_user_message_message_id;
ALTER TABLE user_message DROP FOREIGN KEY fk_on_user_message_updated_user_id;
ALTER TABLE user_message DROP FOREIGN KEY fk_on_user_message_user_id;
ALTER TABLE user_membership DROP FOREIGN KEY fk_on_membership_id;
ALTER TABLE user_membership DROP FOREIGN KEY fk_on_user_id;
ALTER TABLE user_membership DROP FOREIGN KEY fk_on_user_membership_created_user_id;
ALTER TABLE user_membership DROP FOREIGN KEY fk_on_user_membership_updated_user_id;
ALTER TABLE user_document DROP FOREIGN KEY fk_on_user_document_created_user_id;
ALTER TABLE user_document DROP FOREIGN KEY fk_on_user_document_updated_user_id;
ALTER TABLE user_document DROP FOREIGN KEY fk_user_document_on_document_id;
ALTER TABLE user_document DROP FOREIGN KEY fk_user_document_on_user_id;
ALTER TABLE skill DROP FOREIGN KEY fk_on_skill_created_user_id;
ALTER TABLE skill DROP FOREIGN KEY fk_on_skill_updated_user_id;
ALTER TABLE skill DROP FOREIGN KEY fk_skill_on_industry_id;
ALTER TABLE message DROP FOREIGN KEY fk_on_message_created_user_id;
ALTER TABLE message DROP FOREIGN KEY fk_on_message_message_id;
ALTER TABLE message DROP FOREIGN KEY fk_on_message_sender_user_id;
ALTER TABLE message DROP FOREIGN KEY fk_on_message_updated_user_id;
ALTER TABLE message_recipient DROP FOREIGN KEY fk_on_message_recipient_created_user_id;
ALTER TABLE message_recipient DROP FOREIGN KEY fk_on_message_recipient_message_id;
ALTER TABLE message_recipient DROP FOREIGN KEY fk_on_message_recipient_updated_user_id;
ALTER TABLE message_recipient DROP FOREIGN KEY fk_on_message_recipient_user_id;
ALTER TABLE message_box DROP FOREIGN KEY fk_on_message_box_created_user_id;
ALTER TABLE message_box DROP FOREIGN KEY fk_on_message_box_updated_user_id;
ALTER TABLE message_box DROP FOREIGN KEY fk_on_message_box_user_id;
ALTER TABLE membership DROP FOREIGN KEY fk_on_membership_created_user_id;
ALTER TABLE membership DROP FOREIGN KEY fk_on_membership_updated_user_id;
ALTER TABLE industry DROP FOREIGN KEY fk_on_industry_created_user_id;
ALTER TABLE industry DROP FOREIGN KEY fk_on_industry_updated_user_id;
ALTER TABLE domain DROP FOREIGN KEY fk_on_domain_created_user_id;
ALTER TABLE domain DROP FOREIGN KEY fk_on_domain_updated_user_id;
ALTER TABLE domain DROP FOREIGN KEY fk_on_skill_industry_id;
ALTER TABLE document DROP FOREIGN KEY fk_on_document_created_user_id;
ALTER TABLE document DROP FOREIGN KEY fk_on_document_updated_user_id;
ALTER TABLE document_tag DROP FOREIGN KEY fk_on_document_tag_created_user_id;
ALTER TABLE document_tag DROP FOREIGN KEY fk_on_document_tag_document_id;
ALTER TABLE document_tag DROP FOREIGN KEY fk_on_document_tag_tag_id;
ALTER TABLE document_tag DROP FOREIGN KEY fk_on_document_tag_updated_user_id;
ALTER TABLE document_tag DROP FOREIGN KEY fk_on_document_tag_user_document_id;
ALTER TABLE document_tag DROP FOREIGN KEY fk_on_document_tag_user_id;
ALTER TABLE document_search DROP FOREIGN KEY fk_on_document_search_created_user_id;
ALTER TABLE document_search DROP FOREIGN KEY fk_on_document_search_updated_user_id;
ALTER TABLE document_search DROP FOREIGN KEY fk_on_document_search_user_id;
ALTER TABLE contact DROP FOREIGN KEY fk_on_contact_contact_user_id;
ALTER TABLE contact DROP FOREIGN KEY fk_on_contact_created_user_id;
ALTER TABLE contact DROP FOREIGN KEY fk_on_contact_updated_user_id;
ALTER TABLE adviser DROP FOREIGN KEY fk_on_adviser_adviser_user_id;
ALTER TABLE adviser DROP FOREIGN KEY fk_on_adviser_created_user_id;
ALTER TABLE adviser DROP FOREIGN KEY fk_on_adviser_updated_user_id;
drop table `user`;
drop table `user_tag`;
ALTER TABLE user_skill DROP PRIMARY KEY;
drop table `user_skill`;
ALTER TABLE user_message DROP PRIMARY KEY;
drop table `user_message`;
drop table `user_membership`;
drop table `user_document`;
drop table `skill`;
drop table `message`;
ALTER TABLE message_recipient DROP PRIMARY KEY;
drop table `message_recipient`;
drop table `message_box`;
drop table `membership`;
drop table `industry`;
drop table `domain`;
drop table `document`;
drop table `document_tag`;
drop table `document_search`;
drop table `country`;
ALTER TABLE contact DROP PRIMARY KEY;
drop table `contact`;
drop table `config`;
ALTER TABLE adviser DROP PRIMARY KEY;
drop table `adviser`;

