#!/bin/sh
### BEGIN INIT INFO
## END INIT INFO
 
# Path to play install folder
ACTIVATOR_HOME=/usr/lib/activator-install/activator
ACTIVATOR=activator
START_APP=target/universal/stage/bin/spider-app

export PATH=$PATH:$ACTIVATOR_HOME

# set jvm memory size 
export JAVA_OPTS="-Xms624m -Xmx624m"
 
# Path to the JVM
JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
export JAVA_HOME
 
# User running the Play process
USER=ubuntu
 
# Path to the application
APPLICATION_PATH=/usr/lib/spider-app
 
. /lib/lsb/init-functions
 
case "$1" in
    start)
        cd ${APPLICATION_PATH}
        echo -n "Staging Play service: "
        $ACTIVATOR clean stage
        echo -n "Starting Play service: "
        rm -f ${APPLICATION_PATH}/server.pid
        #su $USER -c "${ACTIVATOR} start ${APPLICATION_PATH} --%production >/dev/null"
        #su $USER -c "${ACTIVATOR} start >/dev/null"
        su $USER -c "${START_APP}"
        RETVAL=$?
 
        # You may want to start more applications as follows
        # [ $RETVAL -eq 0 ] && su $USER -c "${ACTIVATOR} start application2"
        # RETVAL=$?
 
        if [ $RETVAL -eq 0 ]; then
            log_end_msg 0
        else
            log_end_msg 1
        fi  
        ;;  
    stop)
        echo -n "Shutting down Play service: "
        #${ACTIVATOR} stop ${APPLICATION_PATH} > /dev/null
        cd ${APPLICATION_PATH}
        #${ACTIVATOR} stop > /dev/null
        ${ACTIVATOR} stop
        # ${ACTIVATOR} stop application2 > /dev/null
 
        RETVAL=$?
 
        if [ $RETVAL -eq 0 ]; then
            log_end_msg 0
        else
            log_end_msg 1
        fi
        ;;
    status)
        ${ACTIVATOR} status ${APPLICATION_PATH}
        RETVAL=$?
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|status}" >&2
        exit 1
        ;;
esac
 
exit 0